server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /static/ {
        try_files $uri =404;
    }

    location ~ \.(js|css|map|ico|svg|ttf|woff|woff2|png|jpg|jpeg|webp)$ {
        try_files $uri =404;
    }
}
