services:
    - type: static
      name: landmarks-frontend
      env: static
      plan: free
      region: frankfurt
      buildCommand: npm run build
      staticPublishPath: dist
      envVars:
          - key: VITE_BACKEND_URL
            value: https://landmarks-backend.davidliviu.com
